token:
symbol:
setNickname: "true"
nicknameHeader: ""
activityMsg: ""
status: 2
refresh: 120

image:
  repository: rssnyder/discord-bot-cryptoprices
  pullPolicy: IfNotPresent
  tag: "a47bdbea290be24d25466227e9526ea7ab4b5cf6"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

resources:
  limits:
    cpu: 10m
    memory: 8Mi
  requests:
    cpu: 1m
    memory: 6Mi

nodeSelector: {}

tolerations: []

affinity: {}
